habitcakesapp/blueprints/userbase/models.py
# modules imports
from flask_login import UserMixin
# app imports
from habitcakesapp.app import db

class User(db.Model, UserMixin):
    __tablename__ = 'users'
    uid = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String, nullable=False)
    password = db.Column(db.String, nullable=False)
    email = db.Column(db.String, nullable=False)
    role = db.Column(db.String,default='user', nullable=False)
    # database relationship
    habits = db.relationship('Habit', back_populates='user')
    # unique constrains for avoiding duplicates
    __table_args__ = (
        db.UniqueConstraint('email', name='_email_uc'),
    )
    # overriding parent classes methods
    def __repr__(self):
        return f'<User: {self.username}, Email: {self.email}>'

    def get_id(self):
        return self.uid

habitcakesapp/blueprints/userbase/routes.py
# modules imports
from flask import render_template, redirect, request, Blueprint, url_for, flash, abort
from flask_login import login_user, logout_user
from sqlalchemy.exc import IntegrityError
# app imports
from habitcakesapp.blueprints.userbase.models import User
from habitcakesapp.app import db, bcrypt

userbase = Blueprint('userbase', __name__, template_folder='templates')

### IMPORTANT! THIS IS A DECOY CREATE ACCOUNT ROUTE - it prevents making new accounts in the demo app
@userbase.route('/create', methods=['GET', 'POST'])
def create():
    if request.method == 'GET':
        return render_template('userbase/create.html')
    abort(403)

### This is proper route to create new users:
# @userbase.route('/create', methods=['GET', 'POST'])
# def create():
#     if request.method == 'GET':
#         return render_template('userbase/create.html')
#     elif request.method == 'POST':
#         name = request.form.get('name')
#         email = request.form.get('email')
#         password = request.form.get('password')
#         # masking the password to store in the database
#         h_password = bcrypt.generate_password_hash(password)
#         # adding the user to database
#         user = User(username=name, password=h_password, email=email)
#         db.session.add(user)
#         try:
#             db.session.commit()
#             return redirect(url_for('userbase.success'))
#         except IntegrityError as e:
#             db.session.rollback()
#             # check if it's an email error
#             if 'email' in str(e.orig):
#                 flash('Konto z podanym adresem e-mail już istnieje!', 'danger')
#             else:
#                 flash('Wystąpił błąd, spróbuj ponownie.', 'danger')
#             return render_template('userbase/create.html')


@userbase.route('/success')
def success():
    return render_template('userbase/success.html')


@userbase.route('/login', methods=['GET','POST'])
def login():
    if request.method == 'GET':
        return render_template('userbase/login.html')
    elif request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')
        # verifying login data
        user = User.query.filter(User.email == email).first()
        if user:
            if bcrypt.check_password_hash(user.password, password):
                login_user(user)
                return redirect(url_for('core.dashboard'))
            else:
                flash('Błędny adres email lub hasło, spróbuj ponownie.', category='danger')
                return render_template('userbase/login.html')
        else:
            flash('Błędny adres email lub hasło, spróbuj ponownie.', category='danger')
            return render_template('userbase/login.html')


@userbase.route('/logout')
def logout():
    logout_user()
    flash('Nastąpiło poprawne wylogowanie', 'success')
    return redirect(url_for('core.index'))

# Temporary route only for demonstrating the app
@userbase.route('/demo')
def info():
    return render_template('userbase/demo.html')

habitcakesapp/blueprints/userbase/templates/userbase/create.html
{% extends "index_base.html" %}
{% block title %}Habitcakess - załóż nowe konto{% endblock %}

{% block content %}

    <section class="section-forms">
    <div class="signup__box form__box">
        <img class="main__logo form__logo" src="{{ url_for('static', filename='img/logo_main.svg') }}" alt="Habitcakes app logo">
        <h1 class="signup__header form__header">Załóż nowe konto</h1>

        <div class="form__flash__box">

            {% with messages = get_flashed_messages(with_categories=true) %}
                {% if messages %}
                    <ul class="form__flash__list">
                        {% for category, message in messages %}
                            <li class="form__flash--{{ category }}">{{ message }}</li>
                        {% endfor %}
                    </ul>
                {% endif %}
            {% endwith %}

        </div>

        <form class="signup__form" action="{{ url_for('userbase.create') }}" method="POST">
            <input class="signup__form--input" type="text" name="name" placeholder="Nazwa użytkownika" required="required">
            <input class="signup__form--input" type="email" name="email" placeholder="Adres e-mail" required="required">
            <input class="signup__form--input" type="password" name="password" placeholder="Hasło" required="required">
{#            <input class="signup__form--button" type="submit" value="Załóż konto">#}
            <a class="signup__form--button demo_anchor" href="{{ url_for('userbase.info') }}">Załóż konto</a>
        </form>
        <a class="signup__link" href="{{ url_for('userbase.login') }}">
                Lub przejdź do strony logowania
        </a>
    </div>
    </section>
{% endblock %}

habitcakesapp/blueprints/userbase/templates/userbase/demo.html
{% extends "index_base.html" %}
{% block title %}Habitcakess - załóż nowe konto{% endblock %}

{% block content %}

    <section class="section-forms">
    <div class="signup__box form__box">
        <img class="main__logo form__logo" src="{{ url_for('static', filename='img/logo_main.svg') }}" alt="Habitcakes app logo">
        <p class="demo_description">To wersja demonstracyjna – rejestracja nowych kont jest wyłączona, więc możesz zalogować się, korzystając z podanych w mailu danych :)</p>
        <a class="demo_signup_link" href="{{ url_for('userbase.login') }}">Przejdź do strony logowania</a>
    </div>
    </section>
{% endblock %}

habitcakesapp/blueprints/userbase/templates/userbase/login.html
{% extends "index_base.html" %}
{% block title %}Habitcakes - logowanie{% endblock %}

{% block content %}
    <main>
    <section class="section-forms">
        <div class="signup__box form__box">
            <img class="main__logo form__logo" src="{{ url_for('static', filename='img/logo_main.svg') }}" alt="Habitcakes app logo">
            <h1 class="signup__header form__header">Zaloguj się</h1>

            <div class="form__flash__box">

            {% with messages = get_flashed_messages(with_categories=true) %}
                {% if messages %}
                    <ul class="form__flash__list">
                        {% for category, message in messages %}
                            <li class="form__flash--{{ category }}">{{ message }}</li>
                        {% endfor %}
                    </ul>
                {% endif %}
            {% endwith %}

        </div>

{#            <p class="signup__fail-message">{{ fail_message }}</p>#}
            <form class="signup__form" action="{{ url_for('userbase.login') }}" method="POST">
                <input class="signup__form--input" type="email" name="email" placeholder="Email" required="required">
                <input class="signup__form--input" type="password" name="password" placeholder="Password" required="required">
                <input class="signup__form--button" type="submit" value="Zaloguj">
            </form>
            <a class="signup__link" href="{{ url_for('userbase.create') }}">
                Lub utwórz nowe konto
            </a>
        </div>
    </section>
    </main>
{% endblock %}

habitcakesapp/blueprints/userbase/templates/userbase/success.html
{% extends "index_base.html" %}
{% block title %}Utworzono nowe konto!{% endblock %}

{% block content %}
    <section class="section-forms">
    <div class="signup__box form__box">
        <img class="main__logo form__logo" src="{{ url_for('static', filename='img/logo_main.svg') }}" alt="Habitcakes app logo">
        <h1 class="signup__header form__header">Utworzono nowe konto!</h1>
        <a class="signup__link" href="{{ url_for('userbase.login') }}">
                Przejdź do strony logowania
        </a>
    </div>
    </section>
{% endblock %}