habitcakesapp/blueprints/userbase/routes.py
# modules imports
from flask import render_template, redirect, request, Blueprint, url_for, flash, abort
from flask_login import login_user, logout_user
from sqlalchemy.exc import IntegrityError
# app imports
from habitcakesapp.blueprints.userbase.models import User
from habitcakesapp.app import db, bcrypt

userbase = Blueprint('userbase', __name__, template_folder='templates')

### IMPORTANT! THIS IS A DECOY CREATE ACCOUNT ROUTE - it prevents making new accounts in the demo app
@userbase.route('/create', methods=['GET', 'POST'])
def create():
    if request.method == 'GET':
        return render_template('userbase/create.html')
    abort(403)

### This is proper route to create new users:
# @userbase.route('/create', methods=['GET', 'POST'])
# def create():
#     if request.method == 'GET':
#         return render_template('userbase/create.html')
#     elif request.method == 'POST':
#         name = request.form.get('name')
#         email = request.form.get('email')
#         password = request.form.get('password')
#         # masking the password to store in the database
#         h_password = bcrypt.generate_password_hash(password)
#         # adding the user to database
#         user = User(username=name, password=h_password, email=email)
#         db.session.add(user)
#         try:
#             db.session.commit()
#             return redirect(url_for('userbase.success'))
#         except IntegrityError as e:
#             db.session.rollback()
#             # check if it's an email error
#             if 'email' in str(e.orig):
#                 flash('Konto z podanym adresem e-mail już istnieje!', 'danger')
#             else:
#                 flash('Wystąpił błąd, spróbuj ponownie.', 'danger')
#             return render_template('userbase/create.html')


@userbase.route('/success')
def success():
    return render_template('userbase/success.html')


@userbase.route('/login', methods=['GET','POST'])
def login():
    if request.method == 'GET':
        return render_template('userbase/login.html')
    elif request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')
        # verifying login data
        user = User.query.filter(User.email == email).first()
        if user:
            if bcrypt.check_password_hash(user.password, password):
                login_user(user)
                return redirect(url_for('core.dashboard'))
            else:
                flash('Błędny adres email lub hasło, spróbuj ponownie.', category='danger')
                return render_template('userbase/login.html')
        else:
            flash('Błędny adres email lub hasło, spróbuj ponownie.', category='danger')
            return render_template('userbase/login.html')


@userbase.route('/logout')
def logout():
    logout_user()
    flash('Nastąpiło poprawne wylogowanie', 'success')
    return redirect(url_for('core.index'))

# Temporary route only for demonstrating the app
@userbase.route('/demo')
def info():
    return render_template('userbase/demo.html')

habitcakesapp/templates/base.html
<!DOCTYPE html>
<html lang="pl">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Base{% endblock %}</title>
    <link rel="icon" href="{{ url_for('static', filename='img/favicon.svg') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='styles.css') }}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">
</head>
<body>

    <header class="header">
        <div class="header__box wrapper">
            <span class="header__text">Habitcakes</span>
            <a href="{{ url_for('userbase.logout') }}"><button class="header__logout-button">Wyloguj</button></a>
        </div>
    </header>

    {% block content %}{% endblock %}

    <footer class="footer section_padding">
        <div class="footer__box wrapper">
            <a class="footer__link" target="_blank" href="https://github.com/pancake-dave/habitcakes">
                <i class="fa-brands fa-square-github"></i> GitHub
            </a>
        </div>
    </footer>
    <script src="{{ url_for('static', filename='main.js') }}"></script>
    <script src="https://kit.fontawesome.com/915f00f029.js" crossorigin="anonymous"></script>
</body>
</html>

habitcakesapp/templates/index_base.html
<!DOCTYPE html>
<html lang="pl">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Base{% endblock %}</title>
    <link rel="icon" href="{{ url_for('static', filename='img/favicon.svg') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='styles.css') }}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">
</head>
<body>
    <header></header>

    {% block content %}{% endblock %}

    <footer class="footer section_padding">
        <div class="footer__box wrapper">
            <a class="footer__link" target="_blank" href="https://github.com/pancake-dave/habitcakes">
                <i class="fa-brands fa-square-github"></i> GitHub
            </a>
        </div>
    </footer>
{#    <script src="{{ url_for('static', filename='main.js') }}"></script>#}
    <script src="https://kit.fontawesome.com/915f00f029.js" crossorigin="anonymous"></script>
</body>
</html>